# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

Numero = int(input("Digite um numero: "))
Tot = 0

for c in range (1, Numero + 1):
    if Numero % c == 0:
        print("\033[33m", end="")
        Tot += 1
    else:
        print("\033[31m", end="")
    print("{} ".format(c), end="")
    
if Tot == 2:
    print("E por isso ele é PRIMO!")
else:
    print("E por isso ele não é PRIMO!")